// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  public enum GoodsType {
    All = 0,
    WuQi = 1,
    FangJu = 2,
    YaoShui = 3,
    CaiLiao = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端向服务器发送类型
  /// </summary>
  public sealed class C_2_S_Bag_Type_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_Bag_Type_Message> _parser = new pb::MessageParser<C_2_S_Bag_Type_Message>(() => new C_2_S_Bag_Type_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_Bag_Type_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 1;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "goodsType" field.</summary>
    public const int GoodsTypeFieldNumber = 2;
    private global::Games.GoodsType goodsType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.GoodsType GoodsType {
      get { return goodsType_; }
      set {
        goodsType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Port != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Port);
      }
      if (GoodsType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) GoodsType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      if (GoodsType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GoodsType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Port = input.ReadInt32();
            break;
          }
          case 16: {
            goodsType_ = (global::Games.GoodsType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器向客户端发送类型
  /// </summary>
  public sealed class S_2_C_Bag_Type_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_Bag_Type_Message> _parser = new pb::MessageParser<S_2_C_Bag_Type_Message>(() => new S_2_C_Bag_Type_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_Bag_Type_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "goodsType" field.</summary>
    public const int GoodsTypeFieldNumber = 1;
    private global::Games.GoodsType goodsType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.GoodsType GoodsType {
      get { return goodsType_; }
      set {
        goodsType_ = value;
      }
    }

    /// <summary>Field number for the "cellsData" field.</summary>
    public const int CellsDataFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Games.CellsData> _repeated_cellsData_codec
        = pb::FieldCodec.ForMessage(18, global::Games.CellsData.Parser);
    private readonly pbc::RepeatedField<global::Games.CellsData> cellsData_ = new pbc::RepeatedField<global::Games.CellsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.CellsData> CellsData {
      get { return cellsData_; }
    }

    /// <summary>Field number for the "bagCellNum" field.</summary>
    public const int BagCellNumFieldNumber = 3;
    private int bagCellNum_;
    /// <summary>
    ///背包打开格子数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BagCellNum {
      get { return bagCellNum_; }
      set {
        bagCellNum_ = value;
      }
    }

    /// <summary>Field number for the "jieSuoCellNum" field.</summary>
    public const int JieSuoCellNumFieldNumber = 4;
    private int jieSuoCellNum_;
    /// <summary>
    ///可解锁格子数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int JieSuoCellNum {
      get { return jieSuoCellNum_; }
      set {
        jieSuoCellNum_ = value;
      }
    }

    /// <summary>Field number for the "maxCellNum" field.</summary>
    public const int MaxCellNumFieldNumber = 5;
    private int maxCellNum_;
    /// <summary>
    ///全部格子数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxCellNum {
      get { return maxCellNum_; }
      set {
        maxCellNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GoodsType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GoodsType);
      }
      cellsData_.WriteTo(output, _repeated_cellsData_codec);
      if (BagCellNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(BagCellNum);
      }
      if (JieSuoCellNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(JieSuoCellNum);
      }
      if (MaxCellNum != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxCellNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GoodsType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GoodsType);
      }
      size += cellsData_.CalculateSize(_repeated_cellsData_codec);
      if (BagCellNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BagCellNum);
      }
      if (JieSuoCellNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(JieSuoCellNum);
      }
      if (MaxCellNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxCellNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            goodsType_ = (global::Games.GoodsType) input.ReadEnum();
            break;
          }
          case 18: {
            cellsData_.AddEntriesFrom(input, _repeated_cellsData_codec);
            break;
          }
          case 24: {
            BagCellNum = input.ReadInt32();
            break;
          }
          case 32: {
            JieSuoCellNum = input.ReadInt32();
            break;
          }
          case 40: {
            MaxCellNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class CellsData : pb::IMessage {
    private static readonly pb::MessageParser<CellsData> _parser = new pb::MessageParser<CellsData>(() => new CellsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CellsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "gridId" field.</summary>
    public const int GridIdFieldNumber = 1;
    private int gridId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridId {
      get { return gridId_; }
      set {
        gridId_ = value;
      }
    }

    /// <summary>Field number for the "goodId" field.</summary>
    public const int GoodIdFieldNumber = 2;
    private int goodId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodId {
      get { return goodId_; }
      set {
        goodId_ = value;
      }
    }

    /// <summary>Field number for the "nowNum" field.</summary>
    public const int NowNumFieldNumber = 3;
    private int nowNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NowNum {
      get { return nowNum_; }
      set {
        nowNum_ = value;
      }
    }

    /// <summary>Field number for the "cellState" field.</summary>
    public const int CellStateFieldNumber = 4;
    private int cellState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CellState {
      get { return cellState_; }
      set {
        cellState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GridId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GridId);
      }
      if (GoodId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GoodId);
      }
      if (NowNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(NowNum);
      }
      if (CellState != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CellState);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GridId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridId);
      }
      if (GoodId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodId);
      }
      if (NowNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NowNum);
      }
      if (CellState != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellState);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GridId = input.ReadInt32();
            break;
          }
          case 16: {
            GoodId = input.ReadInt32();
            break;
          }
          case 24: {
            NowNum = input.ReadInt32();
            break;
          }
          case 32: {
            CellState = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器返回用户数据
  /// </summary>
  public sealed class S_2_C_User_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_User_Message> _parser = new pb::MessageParser<S_2_C_User_Message>(() => new S_2_C_User_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_User_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 1;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    /// <summary>Field number for the "krJuanNum" field.</summary>
    public const int KrJuanNumFieldNumber = 2;
    private int krJuanNum_;
    /// <summary>
    ///拥有的扩容卷
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int KrJuanNum {
      get { return krJuanNum_; }
      set {
        krJuanNum_ = value;
      }
    }

    /// <summary>Field number for the "delJuanNum" field.</summary>
    public const int DelJuanNumFieldNumber = 3;
    private int delJuanNum_;
    /// <summary>
    ///需要消耗的扩容卷数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DelJuanNum {
      get { return delJuanNum_; }
      set {
        delJuanNum_ = value;
      }
    }

    /// <summary>Field number for the "coinNum" field.</summary>
    public const int CoinNumFieldNumber = 4;
    private int coinNum_;
    /// <summary>
    ///拥有的金币数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CoinNum {
      get { return coinNum_; }
      set {
        coinNum_ = value;
      }
    }

    /// <summary>Field number for the "zsNum" field.</summary>
    public const int ZsNumFieldNumber = 5;
    private int zsNum_;
    /// <summary>
    ///拥有的钻石数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ZsNum {
      get { return zsNum_; }
      set {
        zsNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Port != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Port);
      }
      if (KrJuanNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(KrJuanNum);
      }
      if (DelJuanNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(DelJuanNum);
      }
      if (CoinNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CoinNum);
      }
      if (ZsNum != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ZsNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      if (KrJuanNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(KrJuanNum);
      }
      if (DelJuanNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DelJuanNum);
      }
      if (CoinNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CoinNum);
      }
      if (ZsNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ZsNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Port = input.ReadInt32();
            break;
          }
          case 16: {
            KrJuanNum = input.ReadInt32();
            break;
          }
          case 24: {
            DelJuanNum = input.ReadInt32();
            break;
          }
          case 32: {
            CoinNum = input.ReadInt32();
            break;
          }
          case 40: {
            ZsNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端发送购买扩充卷请求
  /// </summary>
  public sealed class C_T_S_BuyAddCellJuan_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_T_S_BuyAddCellJuan_Message> _parser = new pb::MessageParser<C_T_S_BuyAddCellJuan_Message>(() => new C_T_S_BuyAddCellJuan_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_T_S_BuyAddCellJuan_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 1;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Port != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Port);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Port = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器回馈购买扩充卷请求
  /// </summary>
  public sealed class S_T_C_BuyAddCellJuan_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_T_C_BuyAddCellJuan_Message> _parser = new pb::MessageParser<S_T_C_BuyAddCellJuan_Message>(() => new S_T_C_BuyAddCellJuan_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_T_C_BuyAddCellJuan_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "krJuanNum" field.</summary>
    public const int KrJuanNumFieldNumber = 1;
    private int krJuanNum_;
    /// <summary>
    ///拥有的扩容卷
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int KrJuanNum {
      get { return krJuanNum_; }
      set {
        krJuanNum_ = value;
      }
    }

    /// <summary>Field number for the "zsNum" field.</summary>
    public const int ZsNumFieldNumber = 2;
    private int zsNum_;
    /// <summary>
    ///拥有的钻石数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ZsNum {
      get { return zsNum_; }
      set {
        zsNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (KrJuanNum != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(KrJuanNum);
      }
      if (ZsNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ZsNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KrJuanNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(KrJuanNum);
      }
      if (ZsNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ZsNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            KrJuanNum = input.ReadInt32();
            break;
          }
          case 16: {
            ZsNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 客户端向服务器发送扩充背包请求
  /// </summary>
  public sealed class C_T_S_AddBagCell_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_T_S_AddBagCell_Message> _parser = new pb::MessageParser<C_T_S_AddBagCell_Message>(() => new C_T_S_AddBagCell_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_T_S_AddBagCell_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "port" field.</summary>
    public const int PortFieldNumber = 1;
    private int port_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Port {
      get { return port_; }
      set {
        port_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Port != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Port);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Port != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Port);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Port = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器向客户端回馈扩充背包结果
  /// </summary>
  public sealed class S_T_C_AddBagCell_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_T_C_AddBagCell_Message> _parser = new pb::MessageParser<S_T_C_AddBagCell_Message>(() => new S_T_C_AddBagCell_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_T_C_AddBagCell_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "krJuanNum" field.</summary>
    public const int KrJuanNumFieldNumber = 1;
    private int krJuanNum_;
    /// <summary>
    ///拥有的扩容卷
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int KrJuanNum {
      get { return krJuanNum_; }
      set {
        krJuanNum_ = value;
      }
    }

    /// <summary>Field number for the "delJuanNum" field.</summary>
    public const int DelJuanNumFieldNumber = 2;
    private int delJuanNum_;
    /// <summary>
    ///需要消耗的扩容卷数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DelJuanNum {
      get { return delJuanNum_; }
      set {
        delJuanNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (KrJuanNum != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(KrJuanNum);
      }
      if (DelJuanNum != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DelJuanNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (KrJuanNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(KrJuanNum);
      }
      if (DelJuanNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DelJuanNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            KrJuanNum = input.ReadInt32();
            break;
          }
          case 16: {
            DelJuanNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
