// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  /// <summary>
  /// 背包类型
  /// </summary>
  public enum BagType {
    All = 0,
    Weapon = 1,
    Material = 2,
    Armor = 3,
    Medicine = 4,
  }

  /// <summary>
  /// 排序规则
  /// </summary>
  public enum SortRule {
    Default = 0,
    Level = 1,
    Price = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 背包物品数据
  /// </summary>
  public sealed class BagGoodsData : pb::IMessage {
    private static readonly pb::MessageParser<BagGoodsData> _parser = new pb::MessageParser<BagGoodsData>(() => new BagGoodsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagGoodsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "ItemUID" field.</summary>
    public const int ItemUIDFieldNumber = 1;
    private long itemUID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ItemUID {
      get { return itemUID_; }
      set {
        itemUID_ = value;
      }
    }

    /// <summary>Field number for the "ItemID" field.</summary>
    public const int ItemIDFieldNumber = 2;
    private int itemID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    /// <summary>Field number for the "ItemName" field.</summary>
    public const int ItemNameFieldNumber = 3;
    private string itemName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemName {
      get { return itemName_; }
      set {
        itemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Icon" field.</summary>
    public const int IconFieldNumber = 4;
    private string icon_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Description" field.</summary>
    public const int DescriptionFieldNumber = 5;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MaxStack" field.</summary>
    public const int MaxStackFieldNumber = 6;
    private int maxStack_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxStack {
      get { return maxStack_; }
      set {
        maxStack_ = value;
      }
    }

    /// <summary>Field number for the "Quality" field.</summary>
    public const int QualityFieldNumber = 7;
    private int quality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Quality {
      get { return quality_; }
      set {
        quality_ = value;
      }
    }

    /// <summary>Field number for the "EquipType" field.</summary>
    public const int EquipTypeFieldNumber = 8;
    private string equipType_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EquipType {
      get { return equipType_; }
      set {
        equipType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "GridID" field.</summary>
    public const int GridIDFieldNumber = 9;
    private int gridID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridID {
      get { return gridID_; }
      set {
        gridID_ = value;
      }
    }

    /// <summary>Field number for the "Count" field.</summary>
    public const int CountFieldNumber = 10;
    private int count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "Level" field.</summary>
    public const int LevelFieldNumber = 11;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    /// <summary>Field number for the "CombatPower" field.</summary>
    public const int CombatPowerFieldNumber = 12;
    private int combatPower_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CombatPower {
      get { return combatPower_; }
      set {
        combatPower_ = value;
      }
    }

    /// <summary>Field number for the "UseLevel" field.</summary>
    public const int UseLevelFieldNumber = 13;
    private int useLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UseLevel {
      get { return useLevel_; }
      set {
        useLevel_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemUID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(ItemUID);
      }
      if (ItemID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemID);
      }
      if (ItemName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ItemName);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Icon);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Description);
      }
      if (MaxStack != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MaxStack);
      }
      if (Quality != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Quality);
      }
      if (EquipType.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(EquipType);
      }
      if (GridID != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(GridID);
      }
      if (Count != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Count);
      }
      if (Level != 0) {
        output.WriteRawTag(88);
        output.WriteInt32(Level);
      }
      if (CombatPower != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(CombatPower);
      }
      if (UseLevel != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(UseLevel);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemUID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ItemUID);
      }
      if (ItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemID);
      }
      if (ItemName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemName);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (MaxStack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxStack);
      }
      if (Quality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Quality);
      }
      if (EquipType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EquipType);
      }
      if (GridID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridID);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      if (CombatPower != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CombatPower);
      }
      if (UseLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UseLevel);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ItemUID = input.ReadInt64();
            break;
          }
          case 16: {
            ItemID = input.ReadInt32();
            break;
          }
          case 26: {
            ItemName = input.ReadString();
            break;
          }
          case 34: {
            Icon = input.ReadString();
            break;
          }
          case 42: {
            Description = input.ReadString();
            break;
          }
          case 48: {
            MaxStack = input.ReadInt32();
            break;
          }
          case 56: {
            Quality = input.ReadInt32();
            break;
          }
          case 66: {
            EquipType = input.ReadString();
            break;
          }
          case 72: {
            GridID = input.ReadInt32();
            break;
          }
          case 80: {
            Count = input.ReadInt32();
            break;
          }
          case 88: {
            Level = input.ReadInt32();
            break;
          }
          case 96: {
            CombatPower = input.ReadInt32();
            break;
          }
          case 104: {
            UseLevel = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取背包数据请求
  /// </summary>
  public sealed class C_To_S_Bags : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Bags> _parser = new pb::MessageParser<C_To_S_Bags>(() => new C_To_S_Bags());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Bags> Parser { get { return _parser; } }

    /// <summary>Field number for the "BagType" field.</summary>
    public const int BagTypeFieldNumber = 1;
    private global::Games.BagType bagType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagType BagType {
      get { return bagType_; }
      set {
        bagType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BagType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BagType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BagType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            bagType_ = (global::Games.BagType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 获取背包数据响应
  /// </summary>
  public sealed class S_To_C_Bags : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Bags> _parser = new pb::MessageParser<S_To_C_Bags>(() => new S_To_C_Bags());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Bags> Parser { get { return _parser; } }

    /// <summary>Field number for the "BagType" field.</summary>
    public const int BagTypeFieldNumber = 1;
    private global::Games.BagType bagType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagType BagType {
      get { return bagType_; }
      set {
        bagType_ = value;
      }
    }

    /// <summary>Field number for the "GoodsList" field.</summary>
    public const int GoodsListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Games.BagGoodsData> _repeated_goodsList_codec
        = pb::FieldCodec.ForMessage(18, global::Games.BagGoodsData.Parser);
    private readonly pbc::RepeatedField<global::Games.BagGoodsData> goodsList_ = new pbc::RepeatedField<global::Games.BagGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.BagGoodsData> GoodsList {
      get { return goodsList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BagType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BagType);
      }
      goodsList_.WriteTo(output, _repeated_goodsList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BagType);
      }
      size += goodsList_.CalculateSize(_repeated_goodsList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            bagType_ = (global::Games.BagType) input.ReadEnum();
            break;
          }
          case 18: {
            goodsList_.AddEntriesFrom(input, _repeated_goodsList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 整理背包请求
  /// </summary>
  public sealed class C_2_S_SortBagData : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_SortBagData> _parser = new pb::MessageParser<C_2_S_SortBagData>(() => new C_2_S_SortBagData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_SortBagData> Parser { get { return _parser; } }

    /// <summary>Field number for the "BagType" field.</summary>
    public const int BagTypeFieldNumber = 1;
    private global::Games.BagType bagType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagType BagType {
      get { return bagType_; }
      set {
        bagType_ = value;
      }
    }

    /// <summary>Field number for the "SortRule" field.</summary>
    public const int SortRuleFieldNumber = 2;
    private global::Games.SortRule sortRule_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.SortRule SortRule {
      get { return sortRule_; }
      set {
        sortRule_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BagType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BagType);
      }
      if (SortRule != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) SortRule);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BagType);
      }
      if (SortRule != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) SortRule);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            bagType_ = (global::Games.BagType) input.ReadEnum();
            break;
          }
          case 16: {
            sortRule_ = (global::Games.SortRule) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 整理背包响应
  /// </summary>
  public sealed class S_2_C_SortBagData : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_SortBagData> _parser = new pb::MessageParser<S_2_C_SortBagData>(() => new S_2_C_SortBagData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_SortBagData> Parser { get { return _parser; } }

    /// <summary>Field number for the "BagType" field.</summary>
    public const int BagTypeFieldNumber = 1;
    private global::Games.BagType bagType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagType BagType {
      get { return bagType_; }
      set {
        bagType_ = value;
      }
    }

    /// <summary>Field number for the "MergeCount" field.</summary>
    public const int MergeCountFieldNumber = 2;
    private int mergeCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MergeCount {
      get { return mergeCount_; }
      set {
        mergeCount_ = value;
      }
    }

    /// <summary>Field number for the "NewItemList" field.</summary>
    public const int NewItemListFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Games.BagGoodsData> _repeated_newItemList_codec
        = pb::FieldCodec.ForMessage(26, global::Games.BagGoodsData.Parser);
    private readonly pbc::RepeatedField<global::Games.BagGoodsData> newItemList_ = new pbc::RepeatedField<global::Games.BagGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.BagGoodsData> NewItemList {
      get { return newItemList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (BagType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) BagType);
      }
      if (MergeCount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(MergeCount);
      }
      newItemList_.WriteTo(output, _repeated_newItemList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BagType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) BagType);
      }
      if (MergeCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MergeCount);
      }
      size += newItemList_.CalculateSize(_repeated_newItemList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            bagType_ = (global::Games.BagType) input.ReadEnum();
            break;
          }
          case 16: {
            MergeCount = input.ReadInt32();
            break;
          }
          case 26: {
            newItemList_.AddEntriesFrom(input, _repeated_newItemList_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 出售物品数据
  /// </summary>
  public sealed class SellItemData : pb::IMessage {
    private static readonly pb::MessageParser<SellItemData> _parser = new pb::MessageParser<SellItemData>(() => new SellItemData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SellItemData> Parser { get { return _parser; } }

    /// <summary>Field number for the "GirdID" field.</summary>
    public const int GirdIDFieldNumber = 1;
    private int girdID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GirdID {
      get { return girdID_; }
      set {
        girdID_ = value;
      }
    }

    /// <summary>Field number for the "ItemID" field.</summary>
    public const int ItemIDFieldNumber = 2;
    private int itemID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    /// <summary>Field number for the "SellCount" field.</summary>
    public const int SellCountFieldNumber = 3;
    private int sellCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SellCount {
      get { return sellCount_; }
      set {
        sellCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GirdID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GirdID);
      }
      if (ItemID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemID);
      }
      if (SellCount != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SellCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GirdID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GirdID);
      }
      if (ItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemID);
      }
      if (SellCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SellCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GirdID = input.ReadInt32();
            break;
          }
          case 16: {
            ItemID = input.ReadInt32();
            break;
          }
          case 24: {
            SellCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 出售物品请求
  /// </summary>
  public sealed class C_2_S_SellItem : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_SellItem> _parser = new pb::MessageParser<C_2_S_SellItem>(() => new C_2_S_SellItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_SellItem> Parser { get { return _parser; } }

    /// <summary>Field number for the "AutoSell" field.</summary>
    public const int AutoSellFieldNumber = 1;
    private bool autoSell_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool AutoSell {
      get { return autoSell_; }
      set {
        autoSell_ = value;
      }
    }

    /// <summary>Field number for the "SellQuality" field.</summary>
    public const int SellQualityFieldNumber = 2;
    private int sellQuality_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SellQuality {
      get { return sellQuality_; }
      set {
        sellQuality_ = value;
      }
    }

    /// <summary>Field number for the "SellItems" field.</summary>
    public const int SellItemsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Games.SellItemData> _repeated_sellItems_codec
        = pb::FieldCodec.ForMessage(26, global::Games.SellItemData.Parser);
    private readonly pbc::RepeatedField<global::Games.SellItemData> sellItems_ = new pbc::RepeatedField<global::Games.SellItemData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.SellItemData> SellItems {
      get { return sellItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AutoSell != false) {
        output.WriteRawTag(8);
        output.WriteBool(AutoSell);
      }
      if (SellQuality != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SellQuality);
      }
      sellItems_.WriteTo(output, _repeated_sellItems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AutoSell != false) {
        size += 1 + 1;
      }
      if (SellQuality != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SellQuality);
      }
      size += sellItems_.CalculateSize(_repeated_sellItems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            AutoSell = input.ReadBool();
            break;
          }
          case 16: {
            SellQuality = input.ReadInt32();
            break;
          }
          case 26: {
            sellItems_.AddEntriesFrom(input, _repeated_sellItems_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 出售物品响应
  /// </summary>
  public sealed class S_2_C_SellItem : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_SellItem> _parser = new pb::MessageParser<S_2_C_SellItem>(() => new S_2_C_SellItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_SellItem> Parser { get { return _parser; } }

    /// <summary>Field number for the "Success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "EarnedGold" field.</summary>
    public const int EarnedGoldFieldNumber = 2;
    private int earnedGold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EarnedGold {
      get { return earnedGold_; }
      set {
        earnedGold_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (EarnedGold != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(EarnedGold);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (EarnedGold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EarnedGold);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 16: {
            EarnedGold = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
