// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  public enum EquipType {
    /// <summary>
    ///非装备
    /// </summary>
    No = 0,
    /// <summary>
    ///头部
    /// </summary>
    Head = 1,
    /// <summary>
    ///衣服
    /// </summary>
    Cloth = 2,
    /// <summary>
    ///项链
    /// </summary>
    Necklace = 3,
    /// <summary>
    ///戒指
    /// </summary>
    Ring = 4,
    /// <summary>
    ///护腿
    /// </summary>
    LegGuards = 5,
    /// <summary>
    ///鞋子
    /// </summary>
    Shoes = 6,
  }

  public enum BagType {
    /// <summary>
    ///材料
    /// </summary>
    Material = 0,
    /// <summary>
    ///装备
    /// </summary>
    Equip = 1,
    /// <summary>
    ///药品
    /// </summary>
    Medicine = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端向服务器请求对应类型的背包数据
  /// </summary>
  public sealed class S_To_C_Bags : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Bags> _parser = new pb::MessageParser<S_To_C_Bags>(() => new S_To_C_Bags());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Bags> Parser { get { return _parser; } }

    /// <summary>Field number for the "gridID" field.</summary>
    public const int GridIDFieldNumber = 1;
    private int gridID_;
    /// <summary>
    ///格子ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridID {
      get { return gridID_; }
      set {
        gridID_ = value;
      }
    }

    /// <summary>Field number for the "goodsList" field.</summary>
    public const int GoodsListFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Games.BagGoodsData> _repeated_goodsList_codec
        = pb::FieldCodec.ForMessage(18, global::Games.BagGoodsData.Parser);
    private readonly pbc::RepeatedField<global::Games.BagGoodsData> goodsList_ = new pbc::RepeatedField<global::Games.BagGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.BagGoodsData> GoodsList {
      get { return goodsList_; }
    }

    /// <summary>Field number for the "currencyNums" field.</summary>
    public const int CurrencyNumsFieldNumber = 3;
    private int currencyNums_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CurrencyNums {
      get { return currencyNums_; }
      set {
        currencyNums_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (GridID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(GridID);
      }
      goodsList_.WriteTo(output, _repeated_goodsList_codec);
      if (CurrencyNums != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CurrencyNums);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (GridID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridID);
      }
      size += goodsList_.CalculateSize(_repeated_goodsList_codec);
      if (CurrencyNums != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyNums);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            GridID = input.ReadInt32();
            break;
          }
          case 18: {
            goodsList_.AddEntriesFrom(input, _repeated_goodsList_codec);
            break;
          }
          case 24: {
            CurrencyNums = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class BagGoodsData : pb::IMessage {
    private static readonly pb::MessageParser<BagGoodsData> _parser = new pb::MessageParser<BagGoodsData>(() => new BagGoodsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagGoodsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "itemID" field.</summary>
    public const int ItemIDFieldNumber = 1;
    private int itemID_;
    /// <summary>
    ///物品ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    /// <summary>Field number for the "itemName" field.</summary>
    public const int ItemNameFieldNumber = 2;
    private string itemName_ = "";
    /// <summary>
    ///物品名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ItemName {
      get { return itemName_; }
      set {
        itemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "itemType" field.</summary>
    public const int ItemTypeFieldNumber = 3;
    private global::Games.BagType itemType_ = 0;
    /// <summary>
    ///物品类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagType ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "icon" field.</summary>
    public const int IconFieldNumber = 4;
    private string icon_ = "";
    /// <summary>
    ///物品图片
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Icon {
      get { return icon_; }
      set {
        icon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "des" field.</summary>
    public const int DesFieldNumber = 5;
    private string des_ = "";
    /// <summary>
    ///物品介绍
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Des {
      get { return des_; }
      set {
        des_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "maxStack" field.</summary>
    public const int MaxStackFieldNumber = 6;
    private int maxStack_;
    /// <summary>
    ///最大堆叠数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxStack {
      get { return maxStack_; }
      set {
        maxStack_ = value;
      }
    }

    /// <summary>Field number for the "rarity" field.</summary>
    public const int RarityFieldNumber = 7;
    private int rarity_;
    /// <summary>
    ///稀有度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Rarity {
      get { return rarity_; }
      set {
        rarity_ = value;
      }
    }

    /// <summary>Field number for the "equipType" field.</summary>
    public const int EquipTypeFieldNumber = 8;
    private global::Games.EquipType equipType_ = 0;
    /// <summary>
    ///装备类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.EquipType EquipType {
      get { return equipType_; }
      set {
        equipType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemID);
      }
      if (ItemName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ItemName);
      }
      if (ItemType != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) ItemType);
      }
      if (Icon.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Icon);
      }
      if (Des.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Des);
      }
      if (MaxStack != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MaxStack);
      }
      if (Rarity != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Rarity);
      }
      if (EquipType != 0) {
        output.WriteRawTag(64);
        output.WriteEnum((int) EquipType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemID);
      }
      if (ItemName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemName);
      }
      if (ItemType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ItemType);
      }
      if (Icon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Icon);
      }
      if (Des.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Des);
      }
      if (MaxStack != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxStack);
      }
      if (Rarity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rarity);
      }
      if (EquipType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EquipType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ItemID = input.ReadInt32();
            break;
          }
          case 18: {
            ItemName = input.ReadString();
            break;
          }
          case 24: {
            itemType_ = (global::Games.BagType) input.ReadEnum();
            break;
          }
          case 34: {
            Icon = input.ReadString();
            break;
          }
          case 42: {
            Des = input.ReadString();
            break;
          }
          case 48: {
            MaxStack = input.ReadInt32();
            break;
          }
          case 56: {
            Rarity = input.ReadInt32();
            break;
          }
          case 64: {
            equipType_ = (global::Games.EquipType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
