// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Shop.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  /// <summary>
  ///商品类型
  /// </summary>
  public enum ShopsType {
    EqShop = 0,
    ConsumeShop = 1,
  }

  /// <summary>
  ///商城刷新类型
  /// </summary>
  public enum ShopsUpdateType {
    None = 0,
    /// <summary>
    ///商城的免费刷新次数
    /// </summary>
    FreeUpdate = 1,
    /// <summary>
    ///付费刷新
    /// </summary>
    GlodUpdate = 2,
  }

  public enum ShopBuy_Result {
    Succ = 0,
    NoMoney = 1,
    NoLevel = 2,
    NoFamilyLevel = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端向服务器请求对应类型商城的商品数据
  /// </summary>
  public sealed class C_2_S_SpecialShops : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_SpecialShops> _parser = new pb::MessageParser<C_2_S_SpecialShops>(() => new C_2_S_SpecialShops());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_SpecialShops> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Games.ShopsType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "updateType" field.</summary>
    public const int UpdateTypeFieldNumber = 2;
    private global::Games.ShopsUpdateType updateType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsUpdateType UpdateType {
      get { return updateType_; }
      set {
        updateType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (UpdateType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpdateType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (UpdateType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpdateType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Games.ShopsType) input.ReadEnum();
            break;
          }
          case 16: {
            updateType_ = (global::Games.ShopsUpdateType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器回馈客户端请求对应的商城的商品数据
  /// </summary>
  public sealed class S_2_C_SpecialShops : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_SpecialShops> _parser = new pb::MessageParser<S_2_C_SpecialShops>(() => new S_2_C_SpecialShops());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_SpecialShops> Parser { get { return _parser; } }

    /// <summary>Field number for the "goodsList" field.</summary>
    public const int GoodsListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Games.ShopGoodsDate> _repeated_goodsList_codec
        = pb::FieldCodec.ForMessage(10, global::Games.ShopGoodsDate.Parser);
    private readonly pbc::RepeatedField<global::Games.ShopGoodsDate> goodsList_ = new pbc::RepeatedField<global::Games.ShopGoodsDate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.ShopGoodsDate> GoodsList {
      get { return goodsList_; }
    }

    /// <summary>Field number for the "shopUpdateType" field.</summary>
    public const int ShopUpdateTypeFieldNumber = 2;
    private global::Games.ShopsUpdateType shopUpdateType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsUpdateType ShopUpdateType {
      get { return shopUpdateType_; }
      set {
        shopUpdateType_ = value;
      }
    }

    /// <summary>Field number for the "currencyNums" field.</summary>
    public const int CurrencyNumsFieldNumber = 3;
    private int currencyNums_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CurrencyNums {
      get { return currencyNums_; }
      set {
        currencyNums_ = value;
      }
    }

    /// <summary>Field number for the "glodNums" field.</summary>
    public const int GlodNumsFieldNumber = 4;
    private int glodNums_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GlodNums {
      get { return glodNums_; }
      set {
        glodNums_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      goodsList_.WriteTo(output, _repeated_goodsList_codec);
      if (ShopUpdateType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ShopUpdateType);
      }
      if (CurrencyNums != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CurrencyNums);
      }
      if (GlodNums != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(GlodNums);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += goodsList_.CalculateSize(_repeated_goodsList_codec);
      if (ShopUpdateType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShopUpdateType);
      }
      if (CurrencyNums != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyNums);
      }
      if (GlodNums != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GlodNums);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            goodsList_.AddEntriesFrom(input, _repeated_goodsList_codec);
            break;
          }
          case 16: {
            shopUpdateType_ = (global::Games.ShopsUpdateType) input.ReadEnum();
            break;
          }
          case 24: {
            CurrencyNums = input.ReadInt32();
            break;
          }
          case 32: {
            GlodNums = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class ShopGoodsDate : pb::IMessage {
    private static readonly pb::MessageParser<ShopGoodsDate> _parser = new pb::MessageParser<ShopGoodsDate>(() => new ShopGoodsDate());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopGoodsDate> Parser { get { return _parser; } }

    /// <summary>Field number for the "shopGoodsID" field.</summary>
    public const int ShopGoodsIDFieldNumber = 1;
    private int shopGoodsID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ShopGoodsID {
      get { return shopGoodsID_; }
      set {
        shopGoodsID_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShopGoodsID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShopGoodsID);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShopGoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ShopGoodsID);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ShopGoodsID = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///商城购买商品
  ///1.购买的什么商城
  ///2.购买哪个商品
  ///3.购买的商品数量
  /// </summary>
  public sealed class C_2_S_ShopBuy_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_ShopBuy_Message> _parser = new pb::MessageParser<C_2_S_ShopBuy_Message>(() => new C_2_S_ShopBuy_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_ShopBuy_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "shopType" field.</summary>
    public const int ShopTypeFieldNumber = 1;
    private global::Games.ShopsType shopType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsType ShopType {
      get { return shopType_; }
      set {
        shopType_ = value;
      }
    }

    /// <summary>Field number for the "gridID" field.</summary>
    public const int GridIDFieldNumber = 2;
    private int gridID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridID {
      get { return gridID_; }
      set {
        gridID_ = value;
      }
    }

    /// <summary>Field number for the "goodsID" field.</summary>
    public const int GoodsIDFieldNumber = 3;
    private int goodsID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GoodsID {
      get { return goodsID_; }
      set {
        goodsID_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShopType != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ShopType);
      }
      if (GridID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(GridID);
      }
      if (GoodsID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GoodsID);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShopType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShopType);
      }
      if (GridID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridID);
      }
      if (GoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GoodsID);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            shopType_ = (global::Games.ShopsType) input.ReadEnum();
            break;
          }
          case 16: {
            GridID = input.ReadInt32();
            break;
          }
          case 24: {
            GoodsID = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///生成购买商品结果(服务器最终校验结果,会存到数据库中)
  ///1.结果:是否能购买
  ///2.购买的什么商品类型
  ///3.购买的哪个商品
  ///4.购买的商品数量
  ///5.可以购买的商品最大数量(选填)
  /// </summary>
  public sealed class S_2_C_ShopBuy_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_ShopBuy_Message> _parser = new pb::MessageParser<S_2_C_ShopBuy_Message>(() => new S_2_C_ShopBuy_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_ShopBuy_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private global::Games.ShopBuy_Result r_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopBuy_Result R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "shopType" field.</summary>
    public const int ShopTypeFieldNumber = 2;
    private global::Games.ShopsType shopType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsType ShopType {
      get { return shopType_; }
      set {
        shopType_ = value;
      }
    }

    /// <summary>Field number for the "gridID" field.</summary>
    public const int GridIDFieldNumber = 3;
    private int gridID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int GridID {
      get { return gridID_; }
      set {
        gridID_ = value;
      }
    }

    /// <summary>Field number for the "buyCount" field.</summary>
    public const int BuyCountFieldNumber = 4;
    private int buyCount_;
    /// <summary>
    ///购买数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuyCount {
      get { return buyCount_; }
      set {
        buyCount_ = value;
      }
    }

    /// <summary>Field number for the "buyMaxCount" field.</summary>
    public const int BuyMaxCountFieldNumber = 5;
    private int buyMaxCount_;
    /// <summary>
    ///最大购买数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int BuyMaxCount {
      get { return buyMaxCount_; }
      set {
        buyMaxCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) R);
      }
      if (ShopType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ShopType);
      }
      if (GridID != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(GridID);
      }
      if (BuyCount != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(BuyCount);
      }
      if (BuyMaxCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(BuyMaxCount);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) R);
      }
      if (ShopType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShopType);
      }
      if (GridID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GridID);
      }
      if (BuyCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuyCount);
      }
      if (BuyMaxCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BuyMaxCount);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            r_ = (global::Games.ShopBuy_Result) input.ReadEnum();
            break;
          }
          case 16: {
            shopType_ = (global::Games.ShopsType) input.ReadEnum();
            break;
          }
          case 24: {
            GridID = input.ReadInt32();
            break;
          }
          case 32: {
            BuyCount = input.ReadInt32();
            break;
          }
          case 40: {
            BuyMaxCount = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
