// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  public enum BagCellState {
    User = 0,
    UnUser = 1,
    Lock = 2,
  }

  #endregion

  #region Messages
  public sealed class C_2_S_InitialiazeBag : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_InitialiazeBag> _parser = new pb::MessageParser<C_2_S_InitialiazeBag>(() => new C_2_S_InitialiazeBag());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_InitialiazeBag> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S_2_C_InitialiazeBag : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_InitialiazeBag> _parser = new pb::MessageParser<S_2_C_InitialiazeBag>(() => new S_2_C_InitialiazeBag());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_InitialiazeBag> Parser { get { return _parser; } }

    /// <summary>Field number for the "gold" field.</summary>
    public const int GoldFieldNumber = 1;
    private int gold_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Gold {
      get { return gold_; }
      set {
        gold_ = value;
      }
    }

    /// <summary>Field number for the "masonry" field.</summary>
    public const int MasonryFieldNumber = 2;
    private int masonry_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Masonry {
      get { return masonry_; }
      set {
        masonry_ = value;
      }
    }

    /// <summary>Field number for the "roll" field.</summary>
    public const int RollFieldNumber = 3;
    private int roll_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Roll {
      get { return roll_; }
      set {
        roll_ = value;
      }
    }

    /// <summary>Field number for the "energy" field.</summary>
    public const int EnergyFieldNumber = 4;
    private int energy_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Energy {
      get { return energy_; }
      set {
        energy_ = value;
      }
    }

    /// <summary>Field number for the "MaxBagCount" field.</summary>
    public const int MaxBagCountFieldNumber = 5;
    private int maxBagCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MaxBagCount {
      get { return maxBagCount_; }
      set {
        maxBagCount_ = value;
      }
    }

    /// <summary>Field number for the "NowBagCount" field.</summary>
    public const int NowBagCountFieldNumber = 6;
    private int nowBagCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NowBagCount {
      get { return nowBagCount_; }
      set {
        nowBagCount_ = value;
      }
    }

    /// <summary>Field number for the "CellList" field.</summary>
    public const int CellListFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Games.BagCellDate> _repeated_cellList_codec
        = pb::FieldCodec.ForMessage(58, global::Games.BagCellDate.Parser);
    private readonly pbc::RepeatedField<global::Games.BagCellDate> cellList_ = new pbc::RepeatedField<global::Games.BagCellDate>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.BagCellDate> CellList {
      get { return cellList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Gold != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Gold);
      }
      if (Masonry != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Masonry);
      }
      if (Roll != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Roll);
      }
      if (Energy != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Energy);
      }
      if (MaxBagCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(MaxBagCount);
      }
      if (NowBagCount != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(NowBagCount);
      }
      cellList_.WriteTo(output, _repeated_cellList_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Gold != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Gold);
      }
      if (Masonry != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Masonry);
      }
      if (Roll != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Roll);
      }
      if (Energy != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Energy);
      }
      if (MaxBagCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxBagCount);
      }
      if (NowBagCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NowBagCount);
      }
      size += cellList_.CalculateSize(_repeated_cellList_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Gold = input.ReadInt32();
            break;
          }
          case 16: {
            Masonry = input.ReadInt32();
            break;
          }
          case 24: {
            Roll = input.ReadInt32();
            break;
          }
          case 32: {
            Energy = input.ReadInt32();
            break;
          }
          case 40: {
            MaxBagCount = input.ReadInt32();
            break;
          }
          case 48: {
            NowBagCount = input.ReadInt32();
            break;
          }
          case 58: {
            cellList_.AddEntriesFrom(input, _repeated_cellList_codec);
            break;
          }
        }
      }
    }

  }

  public sealed class BagCellDate : pb::IMessage {
    private static readonly pb::MessageParser<BagCellDate> _parser = new pb::MessageParser<BagCellDate>(() => new BagCellDate());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagCellDate> Parser { get { return _parser; } }

    /// <summary>Field number for the "snowID" field.</summary>
    public const int SnowIDFieldNumber = 1;
    private string snowID_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SnowID {
      get { return snowID_; }
      set {
        snowID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "itemId" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 3;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    /// <summary>Field number for the "cellId" field.</summary>
    public const int CellIdFieldNumber = 4;
    private int cellId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CellId {
      get { return cellId_; }
      set {
        cellId_ = value;
      }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    private global::Games.BagCellState state_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.BagCellState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    /// <summary>Field number for the "isUser" field.</summary>
    public const int IsUserFieldNumber = 8;
    private bool isUser_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsUser {
      get { return isUser_; }
      set {
        isUser_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SnowID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SnowID);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (Num != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Num);
      }
      if (CellId != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CellId);
      }
      if (State != 0) {
        output.WriteRawTag(40);
        output.WriteEnum((int) State);
      }
      if (IsUser != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsUser);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SnowID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SnowID);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      if (CellId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CellId);
      }
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      if (IsUser != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            SnowID = input.ReadString();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            Num = input.ReadInt32();
            break;
          }
          case 32: {
            CellId = input.ReadInt32();
            break;
          }
          case 40: {
            state_ = (global::Games.BagCellState) input.ReadEnum();
            break;
          }
          case 64: {
            IsUser = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  public sealed class C_2_S_GetBagType : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_GetBagType> _parser = new pb::MessageParser<C_2_S_GetBagType>(() => new C_2_S_GetBagType());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_GetBagType> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private int type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Type = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
