// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Bag.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Message {

  #region Enums
  public enum ExpandResult {
    ExpandSuccess = 0,
    /// <summary>
    /// 材料不足
    /// </summary>
    ExpandNotEnoughMaterial = 1,
    /// <summary>
    /// 钻石不足
    /// </summary>
    ExpandNotEnoughDiamond = 2,
    /// <summary>
    /// 已达上限
    /// </summary>
    ExpandMaxReached = 3,
  }

  /// <summary>
  /// 操作结果枚举
  /// </summary>
  public enum EquipResult {
    EquipSuccess = 0,
    /// <summary>
    /// 道具不存在
    /// </summary>
    EquipFailNotExist = 1,
    /// <summary>
    /// 部位错误
    /// </summary>
    EquipFailWrongSlot = 2,
    /// <summary>
    /// 等级不足
    /// </summary>
    EquipFailLevel = 3,
    /// <summary>
    /// 不可卸下（如武器）
    /// </summary>
    EquipFailCannotUnequip = 4,
  }

  /// <summary>
  /// 装备部位枚举
  /// </summary>
  public enum EquipSlot {
    Weapon = 0,
    Head = 1,
    Chest = 2,
    Necklace = 3,
    Ring = 4,
    Legs = 5,
    Boots = 6,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 背包内道具（动态数据）
  /// </summary>
  public sealed class BagItem : pb::IMessage {
    private static readonly pb::MessageParser<BagItem> _parser = new pb::MessageParser<BagItem>(() => new BagItem());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagItem> Parser { get { return _parser; } }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    /// <summary>
    /// 背包内唯一标识
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    /// <summary>
    /// 道具ID，关联静态配置
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 3;
    private int count_;
    /// <summary>
    /// 当前堆叠数量
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "is_new" field.</summary>
    public const int IsNewFieldNumber = 4;
    private bool isNew_;
    /// <summary>
    /// 是否为新获得道具（控制红点）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsNew {
      get { return isNew_; }
      set {
        isNew_ = value;
      }
    }

    /// <summary>Field number for the "extra" field.</summary>
    public const int ExtraFieldNumber = 5;
    private global::Message.ItemExtra extra_;
    /// <summary>
    /// 额外数据（仅装备有效）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.ItemExtra Extra {
      get { return extra_; }
      set {
        extra_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
      if (Count != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Count);
      }
      if (IsNew != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsNew);
      }
      if (extra_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Extra);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      if (IsNew != false) {
        size += 1 + 1;
      }
      if (extra_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Extra);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
          case 24: {
            Count = input.ReadInt32();
            break;
          }
          case 32: {
            IsNew = input.ReadBool();
            break;
          }
          case 42: {
            if (extra_ == null) {
              extra_ = new global::Message.ItemExtra();
            }
            input.ReadMessage(extra_);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 装备额外数据（强化、精炼、镶嵌）
  /// </summary>
  public sealed class ItemExtra : pb::IMessage {
    private static readonly pb::MessageParser<ItemExtra> _parser = new pb::MessageParser<ItemExtra>(() => new ItemExtra());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ItemExtra> Parser { get { return _parser; } }

    /// <summary>Field number for the "enhance_level" field.</summary>
    public const int EnhanceLevelFieldNumber = 1;
    private int enhanceLevel_;
    /// <summary>
    /// 强化等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EnhanceLevel {
      get { return enhanceLevel_; }
      set {
        enhanceLevel_ = value;
      }
    }

    /// <summary>Field number for the "refine_level" field.</summary>
    public const int RefineLevelFieldNumber = 2;
    private int refineLevel_;
    /// <summary>
    /// 精炼等级
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int RefineLevel {
      get { return refineLevel_; }
      set {
        refineLevel_ = value;
      }
    }

    /// <summary>Field number for the "socketed_gems" field.</summary>
    public const int SocketedGemsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_socketedGems_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> socketedGems_ = new pbc::RepeatedField<int>();
    /// <summary>
    /// 已镶嵌的宝石ID列表
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> SocketedGems {
      get { return socketedGems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EnhanceLevel != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EnhanceLevel);
      }
      if (RefineLevel != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(RefineLevel);
      }
      socketedGems_.WriteTo(output, _repeated_socketedGems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EnhanceLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EnhanceLevel);
      }
      if (RefineLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RefineLevel);
      }
      size += socketedGems_.CalculateSize(_repeated_socketedGems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            EnhanceLevel = input.ReadInt32();
            break;
          }
          case 16: {
            RefineLevel = input.ReadInt32();
            break;
          }
          case 26:
          case 24: {
            socketedGems_.AddEntriesFrom(input, _repeated_socketedGems_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 主城背包数据
  /// </summary>
  public sealed class BagData : pb::IMessage {
    private static readonly pb::MessageParser<BagData> _parser = new pb::MessageParser<BagData>(() => new BagData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagData> Parser { get { return _parser; } }

    /// <summary>Field number for the "total_slots" field.</summary>
    public const int TotalSlotsFieldNumber = 1;
    private int totalSlots_;
    /// <summary>
    /// 总格子数（最大240）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int TotalSlots {
      get { return totalSlots_; }
      set {
        totalSlots_ = value;
      }
    }

    /// <summary>Field number for the "unlocked_slots" field.</summary>
    public const int UnlockedSlotsFieldNumber = 2;
    private int unlockedSlots_;
    /// <summary>
    /// 已解锁格子数（初始100）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int UnlockedSlots {
      get { return unlockedSlots_; }
      set {
        unlockedSlots_ = value;
      }
    }

    /// <summary>Field number for the "slot_uids" field.</summary>
    public const int SlotUidsFieldNumber = 3;
    private static readonly pbc::MapField<int, string>.Codec _map_slotUids_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForString(18), 26);
    private readonly pbc::MapField<int, string> slotUids_ = new pbc::MapField<int, string>();
    /// <summary>
    /// 格子索引 -> 道具uid（空槽位无此项）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<int, string> SlotUids {
      get { return slotUids_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TotalSlots != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(TotalSlots);
      }
      if (UnlockedSlots != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(UnlockedSlots);
      }
      slotUids_.WriteTo(output, _map_slotUids_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TotalSlots != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalSlots);
      }
      if (UnlockedSlots != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UnlockedSlots);
      }
      size += slotUids_.CalculateSize(_map_slotUids_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            TotalSlots = input.ReadInt32();
            break;
          }
          case 16: {
            UnlockedSlots = input.ReadInt32();
            break;
          }
          case 26: {
            slotUids_.AddEntriesFrom(input, _map_slotUids_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 已装备的道具（通过BagItem.uid引用）
  /// </summary>
  public sealed class EquippedData : pb::IMessage {
    private static readonly pb::MessageParser<EquippedData> _parser = new pb::MessageParser<EquippedData>(() => new EquippedData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EquippedData> Parser { get { return _parser; } }

    /// <summary>Field number for the "weapon" field.</summary>
    public const int WeaponFieldNumber = 1;
    private string weapon_ = "";
    /// <summary>
    /// 主武器uid，未装备则为空字符串
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Weapon {
      get { return weapon_; }
      set {
        weapon_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "head" field.</summary>
    public const int HeadFieldNumber = 2;
    private string head_ = "";
    /// <summary>
    /// 头盔uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Head {
      get { return head_; }
      set {
        head_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chest" field.</summary>
    public const int ChestFieldNumber = 3;
    private string chest_ = "";
    /// <summary>
    /// 衣服uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Chest {
      get { return chest_; }
      set {
        chest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "necklace" field.</summary>
    public const int NecklaceFieldNumber = 4;
    private string necklace_ = "";
    /// <summary>
    /// 项链uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Necklace {
      get { return necklace_; }
      set {
        necklace_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ring" field.</summary>
    public const int RingFieldNumber = 5;
    private string ring_ = "";
    /// <summary>
    /// 戒指uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Ring {
      get { return ring_; }
      set {
        ring_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "legs" field.</summary>
    public const int LegsFieldNumber = 6;
    private string legs_ = "";
    /// <summary>
    /// 护腿uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Legs {
      get { return legs_; }
      set {
        legs_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "boots" field.</summary>
    public const int BootsFieldNumber = 7;
    private string boots_ = "";
    /// <summary>
    /// 鞋子uid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Boots {
      get { return boots_; }
      set {
        boots_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Weapon.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Weapon);
      }
      if (Head.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Head);
      }
      if (Chest.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Chest);
      }
      if (Necklace.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Necklace);
      }
      if (Ring.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ring);
      }
      if (Legs.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Legs);
      }
      if (Boots.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Boots);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Weapon.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Weapon);
      }
      if (Head.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Head);
      }
      if (Chest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Chest);
      }
      if (Necklace.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Necklace);
      }
      if (Ring.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ring);
      }
      if (Legs.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Legs);
      }
      if (Boots.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Boots);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Weapon = input.ReadString();
            break;
          }
          case 18: {
            Head = input.ReadString();
            break;
          }
          case 26: {
            Chest = input.ReadString();
            break;
          }
          case 34: {
            Necklace = input.ReadString();
            break;
          }
          case 42: {
            Ring = input.ReadString();
            break;
          }
          case 50: {
            Legs = input.ReadString();
            break;
          }
          case 58: {
            Boots = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 快捷药品栏
  /// </summary>
  public sealed class QuickDrugSlot : pb::IMessage {
    private static readonly pb::MessageParser<QuickDrugSlot> _parser = new pb::MessageParser<QuickDrugSlot>(() => new QuickDrugSlot());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<QuickDrugSlot> Parser { get { return _parser; } }

    /// <summary>Field number for the "slot_index" field.</summary>
    public const int SlotIndexFieldNumber = 1;
    private int slotIndex_;
    /// <summary>
    /// 槽位索引（0,1）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SlotIndex {
      get { return slotIndex_; }
      set {
        slotIndex_ = value;
      }
    }

    /// <summary>Field number for the "item_id" field.</summary>
    public const int ItemIdFieldNumber = 2;
    private int itemId_;
    /// <summary>
    /// 绑定的药品ID，0表示未绑定
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemId {
      get { return itemId_; }
      set {
        itemId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SlotIndex != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SlotIndex);
      }
      if (ItemId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SlotIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SlotIndex);
      }
      if (ItemId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            SlotIndex = input.ReadInt32();
            break;
          }
          case 16: {
            ItemId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 1. 请求完整背包数据（登录、打开背包时）
  /// </summary>
  public sealed class C2S_GetBackpackData : pb::IMessage {
    private static readonly pb::MessageParser<C2S_GetBackpackData> _parser = new pb::MessageParser<C2S_GetBackpackData>(() => new C2S_GetBackpackData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_GetBackpackData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  /// <summary>
  /// 1. 服务器响应客户端请求完整背包数据
  /// </summary>
  public sealed class S2C_GetBackpackData : pb::IMessage {
    private static readonly pb::MessageParser<S2C_GetBackpackData> _parser = new pb::MessageParser<S2C_GetBackpackData>(() => new S2C_GetBackpackData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_GetBackpackData> Parser { get { return _parser; } }

    /// <summary>Field number for the "main_bag" field.</summary>
    public const int MainBagFieldNumber = 1;
    private global::Message.BagData mainBag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.BagData MainBag {
      get { return mainBag_; }
      set {
        mainBag_ = value;
      }
    }

    /// <summary>Field number for the "equipped" field.</summary>
    public const int EquippedFieldNumber = 2;
    private global::Message.EquippedData equipped_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.EquippedData Equipped {
      get { return equipped_; }
      set {
        equipped_ = value;
      }
    }

    /// <summary>Field number for the "quick_drugs" field.</summary>
    public const int QuickDrugsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Message.QuickDrugSlot> _repeated_quickDrugs_codec
        = pb::FieldCodec.ForMessage(26, global::Message.QuickDrugSlot.Parser);
    private readonly pbc::RepeatedField<global::Message.QuickDrugSlot> quickDrugs_ = new pbc::RepeatedField<global::Message.QuickDrugSlot>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.QuickDrugSlot> QuickDrugs {
      get { return quickDrugs_; }
    }

    /// <summary>Field number for the "all_items" field.</summary>
    public const int AllItemsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Message.BagItem> _repeated_allItems_codec
        = pb::FieldCodec.ForMessage(34, global::Message.BagItem.Parser);
    private readonly pbc::RepeatedField<global::Message.BagItem> allItems_ = new pbc::RepeatedField<global::Message.BagItem>();
    /// <summary>
    /// 所有道具实例（背包中+装备中）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.BagItem> AllItems {
      get { return allItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mainBag_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MainBag);
      }
      if (equipped_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Equipped);
      }
      quickDrugs_.WriteTo(output, _repeated_quickDrugs_codec);
      allItems_.WriteTo(output, _repeated_allItems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mainBag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MainBag);
      }
      if (equipped_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Equipped);
      }
      size += quickDrugs_.CalculateSize(_repeated_quickDrugs_codec);
      size += allItems_.CalculateSize(_repeated_allItems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (mainBag_ == null) {
              mainBag_ = new global::Message.BagData();
            }
            input.ReadMessage(mainBag_);
            break;
          }
          case 18: {
            if (equipped_ == null) {
              equipped_ = new global::Message.EquippedData();
            }
            input.ReadMessage(equipped_);
            break;
          }
          case 26: {
            quickDrugs_.AddEntriesFrom(input, _repeated_quickDrugs_codec);
            break;
          }
          case 34: {
            allItems_.AddEntriesFrom(input, _repeated_allItems_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 2. 请求刷新（分类筛选）
  /// </summary>
  public sealed class C2S_RefreshUI : pb::IMessage {
    private static readonly pb::MessageParser<C2S_RefreshUI> _parser = new pb::MessageParser<C2S_RefreshUI>(() => new C2S_RefreshUI());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_RefreshUI> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 2. 响应刷新（返回当前页签下的道具列表，仍按旧结构，可后续优化）
  /// </summary>
  public sealed class S2C_RefreshUI : pb::IMessage {
    private static readonly pb::MessageParser<S2C_RefreshUI> _parser = new pb::MessageParser<S2C_RefreshUI>(() => new S2C_RefreshUI());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_RefreshUI> Parser { get { return _parser; } }

    /// <summary>Field number for the "nowItems" field.</summary>
    public const int NowItemsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Message.BagItem> _repeated_nowItems_codec
        = pb::FieldCodec.ForMessage(10, global::Message.BagItem.Parser);
    private readonly pbc::RepeatedField<global::Message.BagItem> nowItems_ = new pbc::RepeatedField<global::Message.BagItem>();
    /// <summary>
    /// 注意：这里依然返回BagItem列表，不含位置信息，客户端需自行展示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.BagItem> NowItems {
      get { return nowItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      nowItems_.WriteTo(output, _repeated_nowItems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += nowItems_.CalculateSize(_repeated_nowItems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            nowItems_.AddEntriesFrom(input, _repeated_nowItems_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 3. 穿脱装备请求
  /// </summary>
  public sealed class C2S_Apparel : pb::IMessage {
    private static readonly pb::MessageParser<C2S_Apparel> _parser = new pb::MessageParser<C2S_Apparel>(() => new C2S_Apparel());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_Apparel> Parser { get { return _parser; } }

    /// <summary>Field number for the "uId" field.</summary>
    public const int UIdFieldNumber = 1;
    private string uId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UId {
      get { return uId_; }
      set {
        uId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private global::Message.EquipSlot slot_ = 0;
    /// <summary>
    /// 装备部位
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.EquipSlot Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "is_unequip" field.</summary>
    public const int IsUnequipFieldNumber = 3;
    private bool isUnequip_;
    /// <summary>
    /// true表示卸下，false表示装备/替换
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsUnequip {
      get { return isUnequip_; }
      set {
        isUnequip_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UId);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Slot);
      }
      if (IsUnequip != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsUnequip);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UId);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Slot);
      }
      if (IsUnequip != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            UId = input.ReadString();
            break;
          }
          case 16: {
            slot_ = (global::Message.EquipSlot) input.ReadEnum();
            break;
          }
          case 24: {
            IsUnequip = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 3. 穿脱装备响应
  /// </summary>
  public sealed class S2C_Apparel : pb::IMessage {
    private static readonly pb::MessageParser<S2C_Apparel> _parser = new pb::MessageParser<S2C_Apparel>(() => new S2C_Apparel());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_Apparel> Parser { get { return _parser; } }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Message.EquipResult result_ = 0;
    /// <summary>
    /// 操作结果
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.EquipResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "slot" field.</summary>
    public const int SlotFieldNumber = 2;
    private global::Message.EquipSlot slot_ = 0;
    /// <summary>
    /// 部位
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.EquipSlot Slot {
      get { return slot_; }
      set {
        slot_ = value;
      }
    }

    /// <summary>Field number for the "new_item_uid" field.</summary>
    public const int NewItemUidFieldNumber = 3;
    private string newItemUid_ = "";
    /// <summary>
    /// 新装备的uid（卸下时为空）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NewItemUid {
      get { return newItemUid_; }
      set {
        newItemUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "old_item_uid" field.</summary>
    public const int OldItemUidFieldNumber = 4;
    private string oldItemUid_ = "";
    /// <summary>
    /// 被替换的旧装备uid（如有）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OldItemUid {
      get { return oldItemUid_; }
      set {
        oldItemUid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Slot != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Slot);
      }
      if (NewItemUid.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NewItemUid);
      }
      if (OldItemUid.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(OldItemUid);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Slot != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Slot);
      }
      if (NewItemUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NewItemUid);
      }
      if (OldItemUid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OldItemUid);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::Message.EquipResult) input.ReadEnum();
            break;
          }
          case 16: {
            slot_ = (global::Message.EquipSlot) input.ReadEnum();
            break;
          }
          case 26: {
            NewItemUid = input.ReadString();
            break;
          }
          case 34: {
            OldItemUid = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 4. 扩容请求
  /// </summary>
  public sealed class C2S_Dilatationl : pb::IMessage {
    private static readonly pb::MessageParser<C2S_Dilatationl> _parser = new pb::MessageParser<C2S_Dilatationl>(() => new C2S_Dilatationl());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_Dilatationl> Parser { get { return _parser; } }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 1;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Num != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 4. 服务器-扩容请求
  /// </summary>
  public sealed class S2S_Dilatationl : pb::IMessage {
    private static readonly pb::MessageParser<S2S_Dilatationl> _parser = new pb::MessageParser<S2S_Dilatationl>(() => new S2S_Dilatationl());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2S_Dilatationl> Parser { get { return _parser; } }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Message.ExpandResult result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.ExpandResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "all" field.</summary>
    public const int AllFieldNumber = 2;
    private int all_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int All {
      get { return all_; }
      set {
        all_ = value;
      }
    }

    /// <summary>Field number for the "now" field.</summary>
    public const int NowFieldNumber = 3;
    private int now_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Now {
      get { return now_; }
      set {
        now_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (All != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(All);
      }
      if (Now != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Now);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (All != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(All);
      }
      if (Now != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Now);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::Message.ExpandResult) input.ReadEnum();
            break;
          }
          case 16: {
            All = input.ReadInt32();
            break;
          }
          case 24: {
            Now = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///更新UI
  /// </summary>
  public sealed class C2S_GXUI : pb::IMessage {
    private static readonly pb::MessageParser<C2S_GXUI> _parser = new pb::MessageParser<C2S_GXUI>(() => new C2S_GXUI());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_GXUI> Parser { get { return _parser; } }

    /// <summary>Field number for the "ChangeMoney" field.</summary>
    public const int ChangeMoneyFieldNumber = 1;
    private int changeMoney_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChangeMoney {
      get { return changeMoney_; }
      set {
        changeMoney_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ChangeMoney != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ChangeMoney);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ChangeMoney != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChangeMoney);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ChangeMoney = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///更新UI
  /// </summary>
  public sealed class S2C_GXUI : pb::IMessage {
    private static readonly pb::MessageParser<S2C_GXUI> _parser = new pb::MessageParser<S2C_GXUI>(() => new S2C_GXUI());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_GXUI> Parser { get { return _parser; } }

    /// <summary>Field number for the "Money" field.</summary>
    public const int MoneyFieldNumber = 1;
    private int money_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Money {
      get { return money_; }
      set {
        money_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Money != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Money);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Money != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Money);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Money = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class C2S_SellGood : pb::IMessage {
    private static readonly pb::MessageParser<C2S_SellGood> _parser = new pb::MessageParser<C2S_SellGood>(() => new C2S_SellGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C2S_SellGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private string uid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num" field.</summary>
    public const int NumFieldNumber = 2;
    private int num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Uid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Uid);
      }
      if (Num != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Num);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Num);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Uid = input.ReadString();
            break;
          }
          case 16: {
            Num = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class S2C_SellGood : pb::IMessage {
    private static readonly pb::MessageParser<S2C_SellGood> _parser = new pb::MessageParser<S2C_SellGood>(() => new S2C_SellGood());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S2C_SellGood> Parser { get { return _parser; } }

    /// <summary>Field number for the "main_bag" field.</summary>
    public const int MainBagFieldNumber = 1;
    private global::Message.BagData mainBag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.BagData MainBag {
      get { return mainBag_; }
      set {
        mainBag_ = value;
      }
    }

    /// <summary>Field number for the "equipped" field.</summary>
    public const int EquippedFieldNumber = 2;
    private global::Message.EquippedData equipped_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Message.EquippedData Equipped {
      get { return equipped_; }
      set {
        equipped_ = value;
      }
    }

    /// <summary>Field number for the "quick_drugs" field.</summary>
    public const int QuickDrugsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Message.QuickDrugSlot> _repeated_quickDrugs_codec
        = pb::FieldCodec.ForMessage(26, global::Message.QuickDrugSlot.Parser);
    private readonly pbc::RepeatedField<global::Message.QuickDrugSlot> quickDrugs_ = new pbc::RepeatedField<global::Message.QuickDrugSlot>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.QuickDrugSlot> QuickDrugs {
      get { return quickDrugs_; }
    }

    /// <summary>Field number for the "all_items" field.</summary>
    public const int AllItemsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Message.BagItem> _repeated_allItems_codec
        = pb::FieldCodec.ForMessage(34, global::Message.BagItem.Parser);
    private readonly pbc::RepeatedField<global::Message.BagItem> allItems_ = new pbc::RepeatedField<global::Message.BagItem>();
    /// <summary>
    /// 所有道具实例（背包中+装备中）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Message.BagItem> AllItems {
      get { return allItems_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (mainBag_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(MainBag);
      }
      if (equipped_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Equipped);
      }
      quickDrugs_.WriteTo(output, _repeated_quickDrugs_codec);
      allItems_.WriteTo(output, _repeated_allItems_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (mainBag_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MainBag);
      }
      if (equipped_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Equipped);
      }
      size += quickDrugs_.CalculateSize(_repeated_quickDrugs_codec);
      size += allItems_.CalculateSize(_repeated_allItems_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (mainBag_ == null) {
              mainBag_ = new global::Message.BagData();
            }
            input.ReadMessage(mainBag_);
            break;
          }
          case 18: {
            if (equipped_ == null) {
              equipped_ = new global::Message.EquippedData();
            }
            input.ReadMessage(equipped_);
            break;
          }
          case 26: {
            quickDrugs_.AddEntriesFrom(input, _repeated_quickDrugs_codec);
            break;
          }
          case 34: {
            allItems_.AddEntriesFrom(input, _repeated_allItems_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
