// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BagItem.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Messages
  /// <summary>
  ///背包数据
  /// </summary>
  public sealed class BagBaseData : pb::IMessage {
    private static readonly pb::MessageParser<BagBaseData> _parser = new pb::MessageParser<BagBaseData>(() => new BagBaseData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BagBaseData> Parser { get { return _parser; } }

    /// <summary>Field number for the "IsExist" field.</summary>
    public const int IsExistFieldNumber = 1;
    private bool isExist_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsExist {
      get { return isExist_; }
      set {
        isExist_ = value;
      }
    }

    /// <summary>Field number for the "ItemID" field.</summary>
    public const int ItemIDFieldNumber = 2;
    private int itemID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemID {
      get { return itemID_; }
      set {
        itemID_ = value;
      }
    }

    /// <summary>Field number for the "ItemNum" field.</summary>
    public const int ItemNumFieldNumber = 3;
    private int itemNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemNum {
      get { return itemNum_; }
      set {
        itemNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IsExist != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsExist);
      }
      if (ItemID != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ItemID);
      }
      if (ItemNum != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ItemNum);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IsExist != false) {
        size += 1 + 1;
      }
      if (ItemID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemID);
      }
      if (ItemNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemNum);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            IsExist = input.ReadBool();
            break;
          }
          case 16: {
            ItemID = input.ReadInt32();
            break;
          }
          case 24: {
            ItemNum = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///返回当前所有的背包信息
  /// </summary>
  public sealed class S_To_C_Bag : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Bag> _parser = new pb::MessageParser<S_To_C_Bag>(() => new S_To_C_Bag());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Bag> Parser { get { return _parser; } }

    /// <summary>Field number for the "bagData" field.</summary>
    public const int BagDataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Games.BagBaseData> _repeated_bagData_codec
        = pb::FieldCodec.ForMessage(10, global::Games.BagBaseData.Parser);
    private readonly pbc::RepeatedField<global::Games.BagBaseData> bagData_ = new pbc::RepeatedField<global::Games.BagBaseData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.BagBaseData> BagData {
      get { return bagData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      bagData_.WriteTo(output, _repeated_bagData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += bagData_.CalculateSize(_repeated_bagData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            bagData_.AddEntriesFrom(input, _repeated_bagData_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
