// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShopData.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  /// <summary>
  /// 商品类型
  /// </summary>
  public enum ShopsType {
    EquipShop = 0,
    ConsumeShop = 1,
  }

  public enum ShopsUpdateType {
    /// <summary>
    /// 凌晨12点固定刷新一次
    /// </summary>
    None = 0,
    /// <summary>
    /// 对应各类商城的免费次数刷新
    /// </summary>
    FreeUpdate = 1,
    /// <summary>
    /// 货币（是否是充值货币）刷新
    /// </summary>
    GlodUpdate = 2,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 客户端向服务器请求对应类型商城的商品数据
  /// </summary>
  public sealed class C_2_S_SpeciaShops : pb::IMessage {
    private static readonly pb::MessageParser<C_2_S_SpeciaShops> _parser = new pb::MessageParser<C_2_S_SpeciaShops>(() => new C_2_S_SpeciaShops());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_2_S_SpeciaShops> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Games.ShopsType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "updateType" field.</summary>
    public const int UpdateTypeFieldNumber = 2;
    private global::Games.ShopsUpdateType updateType_ = 0;
    /// <summary>
    /// 修复：为字段添加名称
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsUpdateType UpdateType {
      get { return updateType_; }
      set {
        updateType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (UpdateType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) UpdateType);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (UpdateType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) UpdateType);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Games.ShopsType) input.ReadEnum();
            break;
          }
          case 16: {
            updateType_ = (global::Games.ShopsUpdateType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 服务器回馈客户端请求对应的商城的商品数据
  /// </summary>
  public sealed class S_2_C_SpeciaShops : pb::IMessage {
    private static readonly pb::MessageParser<S_2_C_SpeciaShops> _parser = new pb::MessageParser<S_2_C_SpeciaShops>(() => new S_2_C_SpeciaShops());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_2_C_SpeciaShops> Parser { get { return _parser; } }

    /// <summary>Field number for the "goodsList" field.</summary>
    public const int GoodsListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Games.ShopGoodsData> _repeated_goodsList_codec
        = pb::FieldCodec.ForMessage(10, global::Games.ShopGoodsData.Parser);
    private readonly pbc::RepeatedField<global::Games.ShopGoodsData> goodsList_ = new pbc::RepeatedField<global::Games.ShopGoodsData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.ShopGoodsData> GoodsList {
      get { return goodsList_; }
    }

    /// <summary>Field number for the "shopType" field.</summary>
    public const int ShopTypeFieldNumber = 2;
    private global::Games.ShopsUpdateType shopType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ShopsUpdateType ShopType {
      get { return shopType_; }
      set {
        shopType_ = value;
      }
    }

    /// <summary>Field number for the "currencyNums" field.</summary>
    public const int CurrencyNumsFieldNumber = 3;
    private int currencyNums_;
    /// <summary>
    /// 修复：为字段添加类型（这里假设是 int32，可根据实际需求调整）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CurrencyNums {
      get { return currencyNums_; }
      set {
        currencyNums_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      goodsList_.WriteTo(output, _repeated_goodsList_codec);
      if (ShopType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ShopType);
      }
      if (CurrencyNums != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(CurrencyNums);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += goodsList_.CalculateSize(_repeated_goodsList_codec);
      if (ShopType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShopType);
      }
      if (CurrencyNums != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrencyNums);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            goodsList_.AddEntriesFrom(input, _repeated_goodsList_codec);
            break;
          }
          case 16: {
            shopType_ = (global::Games.ShopsUpdateType) input.ReadEnum();
            break;
          }
          case 24: {
            CurrencyNums = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed class ShopGoodsData : pb::IMessage {
    private static readonly pb::MessageParser<ShopGoodsData> _parser = new pb::MessageParser<ShopGoodsData>(() => new ShopGoodsData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopGoodsData> Parser { get { return _parser; } }

    /// <summary>Field number for the "shopGoodsID" field.</summary>
    public const int ShopGoodsIDFieldNumber = 1;
    private int shopGoodsID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ShopGoodsID {
      get { return shopGoodsID_; }
      set {
        shopGoodsID_ = value;
      }
    }

    /// <summary>Field number for the "level" field.</summary>
    public const int LevelFieldNumber = 2;
    private int level_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Level {
      get { return level_; }
      set {
        level_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShopGoodsID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ShopGoodsID);
      }
      if (Level != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Level);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShopGoodsID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ShopGoodsID);
      }
      if (Level != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            ShopGoodsID = input.ReadInt32();
            break;
          }
          case 16: {
            Level = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
