// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  /// <summary>
  ///聊天类型
  /// </summary>
  public enum ChatType {
    World = 0,
    Private = 1,
    Teat = 2,
  }

  /// <summary>
  ///聊天结果
  /// </summary>
  public enum ChatResult {
    Succ = 0,
    /// <summary>
    ///等级不符
    /// </summary>
    NoLevel = 1,
    /// <summary>
    ///禁言
    /// </summary>
    NoSpeak = 2,
    /// <summary>
    ///内容太长
    /// </summary>
    LongSpeat = 3,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端向服务器请求世界聊天
  /// </summary>
  public sealed class C_To_S_Chat_World_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Chat_World_Message> _parser = new pb::MessageParser<C_To_S_Chat_World_Message>(() => new C_To_S_Chat_World_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Chat_World_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Games.ChatType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ChatType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 2;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (TextDesc.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TextDesc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Games.ChatType) input.ReadEnum();
            break;
          }
          case 18: {
            TextDesc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///服务器回馈客户端回馈世界聊天
  /// </summary>
  public sealed class S_To_C_Chat_World_Message : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Chat_World_Message> _parser = new pb::MessageParser<S_To_C_Chat_World_Message>(() => new S_To_C_Chat_World_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Chat_World_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "r" field.</summary>
    public const int RFieldNumber = 1;
    private global::Games.ChatResult r_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ChatResult R {
      get { return r_; }
      set {
        r_ = value;
      }
    }

    /// <summary>Field number for the "chatType" field.</summary>
    public const int ChatTypeFieldNumber = 2;
    private global::Games.ChatType chatType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.ChatType ChatType {
      get { return chatType_; }
      set {
        chatType_ = value;
      }
    }

    /// <summary>Field number for the "speaker" field.</summary>
    public const int SpeakerFieldNumber = 3;
    private string speaker_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Speaker {
      get { return speaker_; }
      set {
        speaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "toSpeaker" field.</summary>
    public const int ToSpeakerFieldNumber = 4;
    private string toSpeaker_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ToSpeaker {
      get { return toSpeaker_; }
      set {
        toSpeaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 5;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (R != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) R);
      }
      if (ChatType != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) ChatType);
      }
      if (Speaker.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Speaker);
      }
      if (ToSpeaker.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(ToSpeaker);
      }
      if (TextDesc.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TextDesc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (R != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) R);
      }
      if (ChatType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ChatType);
      }
      if (Speaker.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Speaker);
      }
      if (ToSpeaker.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ToSpeaker);
      }
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            r_ = (global::Games.ChatResult) input.ReadEnum();
            break;
          }
          case 16: {
            chatType_ = (global::Games.ChatType) input.ReadEnum();
            break;
          }
          case 26: {
            Speaker = input.ReadString();
            break;
          }
          case 34: {
            ToSpeaker = input.ReadString();
            break;
          }
          case 42: {
            TextDesc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///客户端--私聊
  /// </summary>
  public sealed class C_To_S_Chat_Private_Message : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Chat_Private_Message> _parser = new pb::MessageParser<C_To_S_Chat_Private_Message>(() => new C_To_S_Chat_Private_Message());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Chat_Private_Message> Parser { get { return _parser; } }

    /// <summary>Field number for the "speaker" field.</summary>
    public const int SpeakerFieldNumber = 1;
    private string speaker_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Speaker {
      get { return speaker_; }
      set {
        speaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "toSpeaker" field.</summary>
    public const int ToSpeakerFieldNumber = 2;
    private string toSpeaker_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ToSpeaker {
      get { return toSpeaker_; }
      set {
        toSpeaker_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "textDesc" field.</summary>
    public const int TextDescFieldNumber = 3;
    private string textDesc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TextDesc {
      get { return textDesc_; }
      set {
        textDesc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Speaker.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Speaker);
      }
      if (ToSpeaker.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ToSpeaker);
      }
      if (TextDesc.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TextDesc);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Speaker.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Speaker);
      }
      if (ToSpeaker.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ToSpeaker);
      }
      if (TextDesc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TextDesc);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Speaker = input.ReadString();
            break;
          }
          case 18: {
            ToSpeaker = input.ReadString();
            break;
          }
          case 26: {
            TextDesc = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
