// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mail.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Games {

  #region Enums
  /// <summary>
  ///玩家当前状态
  /// </summary>
  public enum MainType {
    /// <summary>
    ///登录
    /// </summary>
    Log = 0,
    /// <summary>
    ///系统
    /// </summary>
    System = 1,
    /// <summary>
    ///在线
    /// </summary>
    Noline = 2,
    /// <summary>
    ///好友
    /// </summary>
    Friend = 3,
    /// <summary>
    ///活动
    /// </summary>
    Activity = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  ///客户端向服务器请求邮件信息
  /// </summary>
  public sealed class C_To_S_Mail : pb::IMessage {
    private static readonly pb::MessageParser<C_To_S_Mail> _parser = new pb::MessageParser<C_To_S_Mail>(() => new C_To_S_Mail());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<C_To_S_Mail> Parser { get { return _parser; } }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Games.MainType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.MainType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            type_ = (global::Games.MainType) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///邮件信息
  /// </summary>
  public sealed class MailData : pb::IMessage {
    private static readonly pb::MessageParser<MailData> _parser = new pb::MessageParser<MailData>(() => new MailData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailData> Parser { get { return _parser; } }

    /// <summary>Field number for the "mailID" field.</summary>
    public const int MailIDFieldNumber = 1;
    private int mailID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MailID {
      get { return mailID_; }
      set {
        mailID_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private global::Games.MailBaseData data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Games.MailBaseData Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    /// <summary>Field number for the "isRead" field.</summary>
    public const int IsReadFieldNumber = 3;
    private bool isRead_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsRead {
      get { return isRead_; }
      set {
        isRead_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MailID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(MailID);
      }
      if (data_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Data);
      }
      if (IsRead != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsRead);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MailID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MailID);
      }
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      if (IsRead != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            MailID = input.ReadInt32();
            break;
          }
          case 18: {
            if (data_ == null) {
              data_ = new global::Games.MailBaseData();
            }
            input.ReadMessage(data_);
            break;
          }
          case 24: {
            IsRead = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///邮件数据
  /// </summary>
  public sealed class MailBaseData : pb::IMessage {
    private static readonly pb::MessageParser<MailBaseData> _parser = new pb::MessageParser<MailBaseData>(() => new MailBaseData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MailBaseData> Parser { get { return _parser; } }

    /// <summary>Field number for the "emailID" field.</summary>
    public const int EmailIDFieldNumber = 1;
    private int emailID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EmailID {
      get { return emailID_; }
      set {
        emailID_ = value;
      }
    }

    /// <summary>Field number for the "title" field.</summary>
    public const int TitleFieldNumber = 2;
    private string title_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Title {
      get { return title_; }
      set {
        title_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "content" field.</summary>
    public const int ContentFieldNumber = 3;
    private string content_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Content {
      get { return content_; }
      set {
        content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isAward" field.</summary>
    public const int IsAwardFieldNumber = 4;
    private bool isAward_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsAward {
      get { return isAward_; }
      set {
        isAward_ = value;
      }
    }

    /// <summary>Field number for the "awardList" field.</summary>
    public const int AwardListFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_awardList_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> awardList_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<int> AwardList {
      get { return awardList_; }
    }

    /// <summary>Field number for the "startTime" field.</summary>
    public const int StartTimeFieldNumber = 6;
    private string startTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StartTime {
      get { return startTime_; }
      set {
        startTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endTime" field.</summary>
    public const int EndTimeFieldNumber = 7;
    private string endTime_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EndTime {
      get { return endTime_; }
      set {
        endTime_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EmailID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(EmailID);
      }
      if (Title.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Title);
      }
      if (Content.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Content);
      }
      if (IsAward != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsAward);
      }
      awardList_.WriteTo(output, _repeated_awardList_codec);
      if (StartTime.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(StartTime);
      }
      if (EndTime.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(EndTime);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EmailID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EmailID);
      }
      if (Title.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Title);
      }
      if (Content.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Content);
      }
      if (IsAward != false) {
        size += 1 + 1;
      }
      size += awardList_.CalculateSize(_repeated_awardList_codec);
      if (StartTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StartTime);
      }
      if (EndTime.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EndTime);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            EmailID = input.ReadInt32();
            break;
          }
          case 18: {
            Title = input.ReadString();
            break;
          }
          case 26: {
            Content = input.ReadString();
            break;
          }
          case 32: {
            IsAward = input.ReadBool();
            break;
          }
          case 42:
          case 40: {
            awardList_.AddEntriesFrom(input, _repeated_awardList_codec);
            break;
          }
          case 50: {
            StartTime = input.ReadString();
            break;
          }
          case 58: {
            EndTime = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///返回当前所有的邮件信息
  /// </summary>
  public sealed class S_To_C_Mail : pb::IMessage {
    private static readonly pb::MessageParser<S_To_C_Mail> _parser = new pb::MessageParser<S_To_C_Mail>(() => new S_To_C_Mail());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<S_To_C_Mail> Parser { get { return _parser; } }

    /// <summary>Field number for the "mailData" field.</summary>
    public const int MailDataFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Games.MailData> _repeated_mailData_codec
        = pb::FieldCodec.ForMessage(10, global::Games.MailData.Parser);
    private readonly pbc::RepeatedField<global::Games.MailData> mailData_ = new pbc::RepeatedField<global::Games.MailData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Games.MailData> MailData {
      get { return mailData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      mailData_.WriteTo(output, _repeated_mailData_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += mailData_.CalculateSize(_repeated_mailData_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            mailData_.AddEntriesFrom(input, _repeated_mailData_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
